Arch:
  name: largeconvnet
  input_dim: 1
  num_classes: 10
  stochastic: false

Dis:
  name: discriminator
  input_dim: 128
  num_classes: 2

Optim:
  name: Adam
  lr: 0.001

DataLoader:
  batch_size: 100
  num_workers: 8
  shuffle: True
  drop_last: True

Trainer:
  device: cuda

