Arch:
  name: largeconvnet
  input_dim: 3
  num_classes: 10
  stochastic: True
  top_bn: false

Optim:
  name: Adam
  lr: 0.001

DataLoader:
  name: cifar10
  aug: false
  batch_size: 256
  num_workers: 16
  shuffle: True
  drop_last: True

Trainer:
  name: vat
  device: cuda
  save_dir: cifar_ada
  max_epoch: 1000
  epoch_decay_start: 880
  eps: 8.5
  use_entropy: false

