Arch:
  name: largeconvnet
  input_dim: 3
  num_classes: 10
  stochastic: True
  top_bn: false

Optim:
  name: Adam
  lr: 0.001

DataLoader:
  name: svhn
  aug: false
  batch_size: 16
  num_workers: 16
  shuffle: True
  drop_last: True

Trainer:
  name: vat
  device: cuda
  save_dir: svhn_first_try
  max_epoch: 120
  epoch_decay_start: 80
  eps: 2.5
  use_entropy: false

